platform: &platform
    platform: android

device_config: &device_config
    android:
        platformName: 'android'
        platformVersion: '14'
        deviceName: 'Android Emulator'
        automationName: 'uiautomator2'
        appPackage: 'org.wordpress.android'
        appActivity: 'org.wordpress.android.ui.WPLaunchActivity'
        noReset: 'True'
        folder: '/Users/username/Desktop/and/smart-boom.apk'

production:
    <<: *platform
    <<: *device_config